### ISSUE TITLE
Can't run on Windows 11

### ISSUE THREAD

**Issue by Suleman-Elahi** [XaFF-XaFF/Cronos-Rootkit#1]
![image](https://user-images.githubusercontent.com/24384996/159471325-40fb427e-f2da-423a-b097-614fd0f1dd38.png)

**Comment by XaFF-XaFF** [comment]
Install Visual C++ Redistributable package for VS2019 or just download VCRUNTIME140D.dll x64 and drag, and drop it into C:\Windows\SysWoW64 folder

**Comment by Suleman-Elahi** [comment]
Still doesn't work

**Comment by XaFF-XaFF** [comment]
This issue is not related to the project. This is problem with your Windows. [Here](https://www.youtube.com/watch?v=2o_0Q_9770U) is a tutorial how to fix it.
