### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MasterCraft6969** [XaFF-XaFF/Cronos-Rootkit#13]
Hey. I hope that you still accept feature requests (if you ever did). I was wondering if there is a way to automate an action. For example:
Cronos.exe /(argument here) /s (for silent background processing)
So you wont have the need to always open the program and so others cant just open the .exe and have ring 0 access.

**Comment by XaFF-XaFF** [comment]
Hello, Cronos rootkit is discontinued. New features will be added to new project: https://github.com/XaFF-XaFF/Black-Angel-Rootkit
