### ISSUE TITLE
Hello, XaFF, I've found that using RemoveTheLinks to hide processes can lead to a system blue screen after a while, with the error code 'CRITICAL STRUCTURE CORRUPTION'. Have you encountered this before? Thanks!

### ISSUE THREAD

**Issue by SyncsoftDevelopers** [XaFF-XaFF/Cronos-Rootkit#15]
Hello, XaFF, I've found that using RemoveTheLinks to hide processes can lead to a system blue screen after a while, with the error code 'CRITICAL STRUCTURE CORRUPTION'. Have you encountered this before? Thanks!

**Comment by XaFF-XaFF** [comment]
Hello, it is cause by PatchGuard, which is a protection embedded into Windows used to check if there were made any changes in the memory. The only possible way to hide process, which is modifying kernel memory and is triggering blue screens, is by disabling PatchGuard with a bootkit.

**Comment by SyncsoftDevelopers** [comment]
Thank you for your answer, I really appreciate it. It's very helpful to me.

**Comment by XaFF-XaFF** [comment]
> Thank you for your answer, I really appreciate it. It's very helpful to me.

No problem!
