### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Ponscripter901** [XaFF-XaFF/Cronos-Rootkit#16]
Hi im new to this i truly do not know how to use this.
If someone can give me a full guide that woud be nice.
My discord user is ponscripter.901.
Please add me and help me.
Thank you.

**Comment by MayukhAmerB** [comment]
If you are new to this , better don't use it. R00tKit is not for beginners

**Comment by Ponscripter901** [comment]
> If you are new to this , better don't use it. R00tKit is not for beginners

ye but i want to learn coud u help me

**Comment by XaFF-XaFF** [comment]
Irrelevant to the project

**Comment by Ponscripter901** [comment]
> Irrelevant to the project

whats your discord
