### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by Sarks0** [XaFF-XaFF/Cronos-Rootkit#2]
![SystremError](https://user-images.githubusercontent.com/5589400/160046335-bede5b28-bb92-45be-a809-5dbd6b6d0291.PNG)

Any idea why this might be happening.

**Comment by VioletteCrew** [comment]
u need to download http://www.microsoft.com/download/en/details.aspx?id=26999

**Comment by XaFF-XaFF** [comment]
This issue is not related to the project. It's problem with your Windows. [Here](https://www.youtube.com/watch?v=3mvKtHA4LYE) is tutorial how to fix it.

**Comment by Sarks0** [comment]
Yeah already did that. no worries, thanks anyway.
