### ISSUE TITLE
Hide Process BSOD on Win 10 (1709 Build 16299.1992)

### ISSUE THREAD

**Issue by 0736b** [XaFF-XaFF/Cronos-Rootkit#4]
What's your windows 10 version in the preview gif?

**Comment by XaFF-XaFF** [comment]
Windows 10 Pro (2004 Build 19041.1415). Check if you have correct ACTIVE_PROCESS_LINKS offset for your Windows 10 version.

**Comment by 0736b** [comment]
Change ACTIVE_PROCESS_LINKS to 0x02E8 and it worked, Thanks
