### ISSUE TITLE
Runtime error: Couldn't open handle to device (2). Check if driver is loaded correctly.

### ISSUE THREAD

**Issue by bill-e-ghote** [XaFF-XaFF/Cronos-Rootkit#6]
Not sure if my error or the application. Please advise.

![image](https://user-images.githubusercontent.com/2491041/161455953-860efab6-399d-4b5f-90c6-da059aeb19c7.png)

**Comment by XaFF-XaFF** [comment]
Firstly you have to load the driver into the kernel then run cdbg.exe

**Comment by bill-e-ghote** [comment]
Got it. Thanks.

**Comment by river7816** [comment]
> Firstly you have to load the driver into the kernel then run cdbg.exe

I have the same question, I know I need to load driver into the kernel but I do not know what tools can I use to do it.

**Comment by XaFF-XaFF** [comment]
@river7816 You can learn from this link: https://www.ired.team/miscellaneous-reversing-forensics/windows-kernel-internals/loading-a-windows-kernel-driver-osr-driver-loader-debugging-with-source-code

**Comment by XaFF-XaFF** [comment]
Or use new [Black Angel Rootkit](https://github.com/XaFF-XaFF/Black-Angel-Rootkit) which can be loaded with [kdmapper](https://github.com/TheCruZ/kdmapper)
