### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Allahisgood** [XaFF-XaFF/Cronos-Rootkit#7]
[+] Opening handle to driver
[-] Couldn't open handle to device (2). Check if driver is loaded correctly.

Mind helping me if possible thanks :)

**Comment by XaFF-XaFF** [comment]
You have to load the .sys file manually. For example with service controller or OSR loader. [Here](https://youtu.be/h6p-Kt-Cx9E) is a tutorial how to setup environment to load unsigned driver such as Cronos.
