### ISSUE TITLE
Can't open driver?

### ISSUE THREAD

**Issue by ekinsipahi** [XaFF-XaFF/Cronos-Rootkit#9]
What is the problem here, what driver is this about?
![Screenshot (10)](https://user-images.githubusercontent.com/22233078/184546763-44b5dcd0-a3b8-458c-b726-f2808bc2e10c.png)

**Comment by c4p-n1ck** [comment]
@ekinmanyak123 did you install the rootkit properly.

---
You, can hit me up in Discord: `|| Swm!G ||#4774`

**Comment by XaFF-XaFF** [comment]
You need to load .sys file into the kernel. https://github.com/XaFF-XaFF/Cronos-Rootkit/issues/7#issuecomment-1126929266
